### ISSUE TITLE
Shoving battle Minigame 

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#108]
You are all scouts equipped with the shortstop, you are in a small area (small enough so you don't need to shove 900 times to win).  

Two outcomes once again for this : 

**(Minigame suggestion) A -** You are in a small circle (kinda like the pyro airblast one) and upon falling you die

Example : 
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/45695904/57985672-c4010000-7a6b-11e9-9009-3e5c00ccc0ec.gif)
 

**(Boss suggestion)** **B -** You are in a ring (like the heavy boxing one), everyone that falls out the ring is considered eliminated. Last one to stay in the ring wins.

Example : 
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/45695904/57985666-b3508a00-7a6b-11e9-9569-bdd7d0a7309b.gif)

**Comment by stevu236** [comment]
This kind of sounds similar to the falling floor boss we already have - except the weapon that does the pushing makes more sense with the shortstop.. 

When did the shortstop get this ability and animations?

**Comment by UrUgli** [comment]
Summer 2016

**Comment by stevu236** [comment]
Cool. I need to think up of a bossgame area that would work for this.

**Comment by safalin1** [comment]
We have playtested an initial version of this microgame and found that it requires players to be precise in order to push a player back. We feel that this does not fit in well with the fast paced nature of the other microgames we currently have implemented. 

As a result, we have decided to cut this from V6. We will close this issue for now, but may revisit it in the future
