### ISSUE TITLE
Small change for the "Stay on the ground" minigame

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#140]
Ok, so this game is mostly hated due to the fact you get killed in a nanosecond without knowing what happened. Problem is, only one or two remain as the winners.
A small change for this would be "Get someone off the ground". Sure you might still dies as fast, but more people will get a point for this change, becaus even if they are dead, the rocket might get someone.

**Comment by stevu236** [comment]
I feel like is also applicable as a bug, because the check for seeing if a player is off the ground is too frequent. It should probably be, if you are in the air for over 1 second then you fail. But as well as that, as the minigame starts, theres a 1 or 2 second grace period were the check is not run.

**Comment by stevu236** [comment]
#144 will also fix this.
