### ISSUE TITLE
Cosmetics support

### ISSUE THREAD

**Issue by Perkzitos** [gemidyne/microtf2#163]
Is it possible to add support for cosmetics?

**Comment by stevu236** [comment]
Hi,

We will need to investigate this one a bit before we have an answer for you - Cosmetics were blocked back in 2014 due to them causing hitches during gameplay while loading the cosmetics.

There was also an issue I believe due to cosmetics carrying across class changes.

We will get back to you if this is something we can re-enable.

**Comment by stevu236** [comment]
I have done some initial testing on this - the issues still seem to persist. However I think that I will add a convar in the next stable version of the gamemode so server operators can opt-in to allow cosmetics. 

I still need to do some extra testing with a few players on a server (rather than just bots)

**Comment by stevu236** [comment]
This has been added and will be released in v3.1.0 - currently there is no ETA on when this will be released as we are trying to finish a new bossgame as part of this update

**Comment by stevu236** [comment]
Apologies for slow updates on release, but this has now been released in Version 4.0. Full release notes here: https://www.gemidyne.com/projects/warioware/release-notes/v4/

**Comment by stevu236** [comment]
Further to the above, I have documented the new convar on this page: https://github.com/gemidyne/microtf2/wiki/Console-Variables 

Please note, with cosmetics turned on, strange cosmetics may have their power levels affected - use with care.
