### ISSUE TITLE
[Sorta bug?] Crushing walls at the end of the "escape the factory" boss minigame

### ISSUE THREAD

**Issue by qli-p** [gemidyne/microtf2#166]
Reason I say sorta bug is because I feel this is more a quirk of the source engine than the actual minigame, or this could be intentional, making this less of a bug report and more of a suggestion but I can't be sure, but its been bugging a lot of people, so this could also act as a sorta suggestion to remove the final crushing walls at the end of the minigame as its a significant difficulty spike compared to everything before it.

Basically what happens is the walls kill people hugging them (or seemingly only near them and not actually touching them) when they retract. I'm talking about the fast crushing walls that act as the second to last obstacle in the minigame, and considering their fast speed it would make sense to hug them in order to pass as soon as the opportunity arises. Instead it kills players who do this, and it almost guarantees all players are killed upon reaching it, often resulting in no one winning the minigame, even when people stay away from the walls and attempt to pass normally.

Players should be able to hug the wall of the crusher and pass through un harmed when it reopens. (Or as a suggestion, either slow down the crusher significantly or remove it entirely). Considering the previous, much slower ceiling crusher does not kill players who hug it while it retracts, and is much easier to get past anyway.

**Comment by stevu236** [comment]
Thanks for reporting this. We will address this as part of the next update.

I agree with your points - and I believe this is occurring due to a workaround in the map so players do take damage when crushed.

With Source, if a player comes between a solid brush and a brush entity, the player will correctly be crushed. 
However, in the case with that crusher on the map, there are two brush entities that are coming together, so the player does not actually get crushed (they get stuck instead). We added a trigger_hurt here to simulate the crush effect, but we will look into reworking this crusher or replacing with a new obstacle due to the timing causing issues.

**Comment by stevu236** [comment]
Just noting some things I need to look at after testing:

- [ ] Increase speed of the crusher
- [ ] Fix bug with getting stuck behind crusher. Possibly entity parent problem
