### ISSUE TITLE
I want to join the translators team

### ISSUE THREAD

**Issue by Doresun** [gemidyne/microtf2#214]
I want to become a translator for the gamemode and provide text for **Russian**.

My Steam Community Profile link is https://steamcommunity.com/id/scientistnot/

- [x] I agree to provide accurate translations for my language.

**Comment by stevu236** [comment]
Hi,

Thanks for your interest in translating the gamemode! In order to contribute translations for the gamemode, there are two approaches you can take; do whatever you feel most comfortable with! 

* The first & easiest way is to use our translation editor at https://www.gemidyne.com/ . This requires you to sign in through Steam (which automatically creates an account linked to your Steam profile). Once this is done, we can then add you as a contributor & translator to the gamemode. If you want to do this approach, please let us know once you signed in and we can assign the permissions and let you know the next steps.
* The other way, is using pull requests on Github. This way is best if you feel more comfortable editing the translation files themselves. To get started this way, send a PR and we'll review!

If you need any help, please let us know :)

**Comment by Doresun** [comment]
Thank you, @stevu236 (sorry for the mention)! I have signed into the website now.

**Comment by stevu236** [comment]
Thanks 👍  I have set the correct permissions on your account. 

If you click the "Logged in as" link at the top right of the screen on gemidyne.com and then click Contribute, you should now see a button stating "Contribute translations". If you don't see this though - I might have missed something so please let me know :-) 

If you want to get notified of when new strings are available to translate, feel free to join our translators steam group: https://steamcommunity.com/groups/wariowareredux_translators

As well as the above group, if you would like to be notified of upcoming test sessions, we have a group for that too: https://steamcommunity.com/groups/microtf2_testers


Note: at the moment any translations submitted will be released in the next major version - 5.0. (hopefully releasing in the next few months)
