### ISSUE TITLE
Escape Route bossgame not marking players as winning the microgame on touching the end zone

### ISSUE THREAD

**Issue by EgocentricPoliceDick** [gemidyne/microtf2#62]
Have experienced this ingame myself - the engineer "escape from the factory" boss microgame is only marking some players as having completed the microgame on touching the endzone.

Looking into it right now with @FortyTwoFortyTwo, will drop info here with a fix once we've got something.

**Comment by stevu236** [comment]
Thanks for having a look into it  - I seen this on the livestream last night.
A trigger_multiple is used to determine if the player is in the win area, and the plugin hooks onto this and looks for clients who activate the trigger. 

It's strange how only some players are being set as winners though - could it be something Source Engine related?

**Comment by EgocentricPoliceDick** [comment]
We're trying something out to attempt to fix it, will drop our stuff here if it works.

**Comment by FortyTwoFortyTwo** [comment]
Not really sure why it broke at the start, but some small changes i did seem to work 100% of the time

this line, use `OnStartTouch` instead of `OnTrigger`
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Bossgames/Bossgame2.sp#L86

several lines, replace several `IsPlayerParticipant[X]` and `PlayerStatus[X]` to use methodmap, which is `X.IsParticipating` and `X.Status` respectively.
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Bossgames/Bossgame2.sp#L101
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Bossgames/Bossgame2.sp#L123
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Bossgames/Bossgame2.sp#L149
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Bossgames/Bossgame2.sp#L153
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Bossgames/Bossgame2.sp#L157
