### ISSUE TITLE
Minigame rotation improvement

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#71]
It would be nice if you could make the minigame rotate in a better way, it gets annoying getting 4 times "jarate an enemy" in the span of 7 minigame rounds when they are a lot more of minigames to play.

**Comment by stevu236** [comment]
Thanks for reporting this. 

We are planning to fix this as part of issue #19. Purely relying on Source's RNG isn't providing a good gameplay experience.

Due to issue #19 covering this issue already, I will close this one as a duplicate. If there is any other feedback you would like to provide regarding this, please add comments to #19.
