### ISSUE TITLE
Floor break boss 

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#75]
I thought of a literal "boss" idea, maybe have Wario (boss can be whatever fits) attacking you and you need to survive X ammount of seconds.

I could take for example this boss from dr_valve_hq where it has 3 phases

First phase: Floor break

![20190323193148_1](https://user-images.githubusercontent.com/45695904/54870143-eabff480-4da2-11e9-8fe8-3dada8900e32.jpg)

Second phase: Lasers

![20190323193218_1](https://user-images.githubusercontent.com/45695904/54870097-6a998f00-4da2-11e9-8d4f-5e9ba4ca231e.jpg)

Third phase: Crits rockets shot towards you

![20190323193240_1](https://user-images.githubusercontent.com/45695904/54870099-72593380-4da2-11e9-9fc0-0050fe8e82a5.jpg)

Now this is just an example so you have an idea of what i'm talking about, im not asking you to copy and paste this. 

If it's wario themed then maybe have his motorbike going towards you or a phase where you enter him (like in the warioware games with the onions and stuff). It should have 3 short phases.

![Prev_Wario-Bike](https://user-images.githubusercontent.com/45695904/54870178-47231400-4da3-11e9-9447-7452fa4d43ca.jpg)

![pas bug](https://user-images.githubusercontent.com/45695904/54870166-32468080-4da3-11e9-9076-e6800502bb93.PNG)

**Comment by stevu236** [comment]
I see, the first phase reminds me of something similar from an achievement map, iirc.

I think these ideas are great, but I think to start with we should focus on 1 phase, otherwise this boss might take a long time to implement. That said, I think the other phases would work better as their own bossgames.

For the reasons above, I think we should focus on the floor break phase. So 9 blocks on the floor, controlled via the plugin. Either questions or symbols could be used on a large display so players have to rush onto the floor panel with that answer or symbol. Then, the other panels can disappear, leaving those on them to be knocked out. Things can then maybe speed up?

This idea can be tweaked or elaborated further, but it is a good starting point.

**Comment by stevu236** [comment]
Final changelist

- [ ] Make blocks slightly larger
- [ ] Lower toxic water to below blocks
- [ ] Make time between rounds decay faster
- [ ] Surrounding area detailing
- [ ] BGM

**Comment by stevu236** [comment]
Note to self: We still haven't tested the weapon hit slowdown - the code has been added though

**Comment by stevu236** [comment]
Extra note to self: Make sure the boss' BGM doesn't result in silence. Probably keeping the BGM we had for boxing for this one

**Comment by stevu236** [comment]
So we tested and the BGM isn't long enough, whoops. Needs fixing but weapon slowdown was fine

**Comment by stevu236** [comment]
Added final bgm courtesy of @Mario6493. Just needs final playtesting
