### ISSUE TITLE
Suggestions for "Break a barrel" minigame

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#79]
Firstly, barrels shouldn't be able to fall off the map, this is extremely annoying knowing you could have won but it fell off. 

Secondly, Spawn more barrels on "Break a barrel" OR make the scout that broke one barrel unable to melee anymore (similar to the "stun someone" minigame and prevents griefing of some sort too)

**Comment by stevu236** [comment]
We're going to rework spawn points for this minigame, but I think preventing people who have already broken a barrel to hit others would make the minigame a bit too easy.

The reason the stun an enemy minigame replaces your bat is due to server lag. Previously players could just keep spamming balls, and this caused severe performance issues for everyone on the server at the time.

**Comment by stevu236** [comment]
I have reworked the spawnpoints for this minigame and the change has been released in 2019.1. Closing this
